// Generated by pnpm worker:build-context -- always runs before tsup in worker:build

import { getUnixNow } from "@northguild/gmt";
import { ALLOWED_MODELS, MAX_MESSAGE_LENGTH } from "../src/chat/constants.js";
import { SYSTEM_PROMPT } from "./docs-context.js";

const DEFAULT_MODEL = ALLOWED_MODELS[0];
const ALLOWED_CHAT_ROLES = new Set(["user", "assistant"]);

// Grouped once here rather than inside the rejection, so the number a caller is
// told about is read from the same constant that is enforced above it.
const MAX_MESSAGE_LENGTH_LABEL = MAX_MESSAGE_LENGTH.toLocaleString("en-US");

// Application-level abuse protection.
const DEFAULT_RATE_LIMIT_MAX = 30;
const DEFAULT_RATE_LIMIT_WINDOW_SECONDS = 60;

// Allowed origins for CORS.
// Production: GitHub Pages static site host (all routes share this origin).
// Development: local Next.js dev server.
const CORS_ORIGINS = ["https://northguild.github.io", "http://localhost:3000"];

function getCorsHeaders(origin: string | null): Record<string, string> {
  const allowed =
    origin !== null && CORS_ORIGINS.includes(origin) ? origin : CORS_ORIGINS[0];
  return {
    "Access-Control-Allow-Origin": allowed,
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
    Vary: "Origin",
  };
}

const GEMINI_BASE = "https://generativelanguage.googleapis.com/v1beta/models";

type RateBucket = { count: number; resetAtMs: number };
const rateLimitBuckets = new Map<string, RateBucket>();
// Prune trigger: if the map exceeds this size, sweep expired entries.
// Prevents unbounded growth from high-cardinality / spoofed client IDs.
const MAX_RATE_BUCKETS = 10_000;

function parsePositiveInt(value: string | undefined, fallback: number): number {
  if (!value) return fallback;
  const n = Number.parseInt(value, 10);
  return Number.isFinite(n) && n > 0 ? n : fallback;
}

function getClientId(request: Request): string {
  const cfConnectingIp = request.headers.get("cf-connecting-ip")?.trim();
  if (cfConnectingIp) return cfConnectingIp;

  const xForwardedFor = request.headers.get("x-forwarded-for");
  if (xForwardedFor) {
    const first = xForwardedFor.split(",")[0]?.trim();
    if (first) return first;
  }

  return "unknown";
}

function checkRateLimit(request: Request, env: Record<string, string>) {
  const max = parsePositiveInt(
    env.WORKER_RATE_LIMIT_MAX,
    DEFAULT_RATE_LIMIT_MAX,
  );
  const windowSeconds = parsePositiveInt(
    env.WORKER_RATE_LIMIT_WINDOW_SECONDS,
    DEFAULT_RATE_LIMIT_WINDOW_SECONDS,
  );
  const windowMs = windowSeconds * 1000;

  const now = getUnixNow();
  const clientId = getClientId(request);
  const bucket = rateLimitBuckets.get(clientId);

  if (!bucket || now >= bucket.resetAtMs) {
    // Prune expired entries if the map is getting large. O(n) only at the cap.
    if (rateLimitBuckets.size >= MAX_RATE_BUCKETS) {
      for (const [id, b] of rateLimitBuckets) {
        if (now >= b.resetAtMs) rateLimitBuckets.delete(id);
      }
    }
    // Hard ceiling: if the map is still full after pruning, the isolate is
    // under a high-cardinality flood. Reject rather than grow unbounded.
    if (rateLimitBuckets.size >= MAX_RATE_BUCKETS) {
      return {
        limited: true as const,
        remaining: 0,
        resetAtMs: now + windowMs,
      };
    }
    rateLimitBuckets.set(clientId, { count: 1, resetAtMs: now + windowMs });
    return {
      limited: false as const,
      remaining: max - 1,
      resetAtMs: now + windowMs,
    };
  }

  if (bucket.count >= max) {
    return {
      limited: true as const,
      remaining: 0,
      resetAtMs: bucket.resetAtMs,
    };
  }

  bucket.count += 1;
  rateLimitBuckets.set(clientId, bucket);
  return {
    limited: false as const,
    remaining: Math.max(0, max - bucket.count),
    resetAtMs: bucket.resetAtMs,
  };
}

type GeminiPart = { text: string };
type GeminiContent = { role: string; parts: GeminiPart[] };

function toGeminiContents(
  messages: Array<{ role: string; content: string }>,
): GeminiContent[] {
  return messages.map((m) => ({
    role: m.role === "assistant" ? "model" : "user",
    parts: [{ text: m.content }],
  }));
}

export default {
  async fetch(request: Request, env: Record<string, string>) {
    const cors = getCorsHeaders(request.headers.get("origin"));

    if (request.method === "OPTIONS") {
      return new Response(null, { status: 204, headers: cors });
    }
    if (request.method !== "POST") {
      return new Response("Not allowed", { status: 405, headers: cors });
    }

    const rateLimit = checkRateLimit(request, env);
    if (rateLimit.limited) {
      return new Response(
        JSON.stringify({
          error:
            "Rate limit exceeded for this worker. Please wait and try again.",
        }),
        {
          status: 429,
          headers: {
            "Content-Type": "application/json",
            "Retry-After": Math.max(
              1,
              Math.ceil((rateLimit.resetAtMs - getUnixNow()) / 1000),
            ).toString(),
            ...cors,
          },
        },
      );
    }

    const key = env.GEMINI_API_KEY;
    if (!key) {
      return new Response(
        JSON.stringify({ error: "GEMINI_API_KEY not configured" }),
        {
          status: 500,
          headers: { "Content-Type": "application/json", ...cors },
        },
      );
    }

    let body: {
      messages?: Array<{ role: string; content: string }>;
      model?: string;
    };
    try {
      body = await request.json();
    } catch {
      return new Response(JSON.stringify({ error: "Invalid JSON" }), {
        status: 400,
        headers: { "Content-Type": "application/json", ...cors },
      });
    }

    const url = new URL(request.url);
    const model = url.searchParams.get("model") ?? body.model ?? DEFAULT_MODEL;

    // ── Input validation ──────────────────────────────────────────────────────
    const messages = body.messages;
    if (!Array.isArray(messages)) {
      return new Response(
        JSON.stringify({ error: "messages must be an array" }),
        {
          status: 400,
          headers: { "Content-Type": "application/json", ...cors },
        },
      );
    }
    if (messages.length > 50) {
      return new Response(
        JSON.stringify({ error: "Too many messages (max 50)" }),
        {
          status: 400,
          headers: { "Content-Type": "application/json", ...cors },
        },
      );
    }
    for (const msg of messages) {
      if (
        typeof msg !== "object" ||
        msg === null ||
        typeof (msg as Record<string, unknown>).role !== "string" ||
        typeof (msg as Record<string, unknown>).content !== "string"
      ) {
        return new Response(
          JSON.stringify({ error: "Invalid message format" }),
          {
            status: 400,
            headers: { "Content-Type": "application/json", ...cors },
          },
        );
      }
      const role = (msg as Record<string, unknown>).role as string;
      if (!ALLOWED_CHAT_ROLES.has(role)) {
        return new Response(
          JSON.stringify({
            error: "Invalid message role (must be user or assistant)",
          }),
          {
            status: 400,
            headers: { "Content-Type": "application/json", ...cors },
          },
        );
      }
      if (
        ((msg as Record<string, unknown>).content as string).length >
        MAX_MESSAGE_LENGTH
      ) {
        return new Response(
          JSON.stringify({
            error: `Message too long (max ${MAX_MESSAGE_LENGTH_LABEL} chars)`,
          }),
          {
            status: 400,
            headers: { "Content-Type": "application/json", ...cors },
          },
        );
      }
    }

    if (!(ALLOWED_MODELS as readonly string[]).includes(model)) {
      return new Response(JSON.stringify({ error: "Model not allowed" }), {
        status: 400,
        headers: { "Content-Type": "application/json", ...cors },
      });
    }

    const geminiBody: Record<string, unknown> = {
      contents: toGeminiContents(body.messages ?? []),
    };
    if (SYSTEM_PROMPT) {
      geminiBody.systemInstruction = { parts: [{ text: SYSTEM_PROMPT }] };
    }

    const endpoint = `${GEMINI_BASE}/${model}:streamGenerateContent?alt=sse&key=${key}`;
    const upstream = await fetch(endpoint, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(geminiBody),
    });

    if (!upstream.ok) {
      let userMessage: string;
      if (upstream.status === 429) {
        let isDaily = false;
        try {
          const errBody = (await upstream.json()) as {
            error?: { message?: string };
          };
          const msg = errBody.error?.message?.toLowerCase() ?? "";
          isDaily =
            msg.includes("daily") ||
            msg.includes("per_day") ||
            msg.includes("per day");
        } catch {
          // couldn't parse — default to the shorter hint
        }
        userMessage = isDaily
          ? "Daily request limit reached for this model — try again tomorrow, or switch to a different model."
          : "Rate limit reached for this model — try again in a minute, or switch to a different model.";
      } else {
        try {
          const errBody = (await upstream.json()) as {
            error?: { status?: string; message?: string };
          };
          const { status, message } = errBody.error ?? {};
          userMessage =
            status && message
              ? `${status}: ${message}`
              : `Request failed (${upstream.status})`;
        } catch {
          userMessage = `Request failed (${upstream.status})`;
        }
      }
      return new Response(JSON.stringify({ error: userMessage }), {
        status: upstream.status,
        headers: { "Content-Type": "application/json", ...cors },
      });
    }

    // Pipe the Gemini SSE stream directly to the client.
    return new Response(upstream.body, {
      status: 200,
      headers: {
        "Content-Type": "text/event-stream",
        "Cache-Control": "no-cache",
        Connection: "keep-alive",
        ...cors,
      },
    });
  },
};
