// AUTO-GENERATED by docs/worker/build-context.mjs — do not edit manually
// Re-run: pnpm --filter docs worker:build-context

export const VALID_DOC_ROUTES: ReadonlySet<string> = new Set([
  "/docs",
  "/docs/changelog",
  "/docs/commands",
  "/docs/commands/branch",
  "/docs/commands/checkout",
  "/docs/commands/cleanup",
  "/docs/commands/config",
  "/docs/commands/list",
  "/docs/commands/open",
  "/docs/commands/remove",
  "/docs/configuration",
  "/docs/faq",
  "/docs/getting-started",
  "/docs/guides",
  "/docs/guides/context-switching",
  "/docs/guides/editor-integration",
  "/docs/guides/env-files",
  "/docs/guides/github-issue-integration",
  "/docs/guides/herdr-spaces",
  "/docs/guides/jira-integration",
  "/docs/guides/team-conventions",
]);
