on:
  release:
    types: [published]

permissions:
  id-token: write # Required for OIDC
  contents: write # Required for creating tags

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    if: github.event.release.draft == false
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org

      - uses: pnpm/action-setup@v4
      - run: pnpm install --frozen-lockfile
      - run: pnpm test
      - run: pnpm build

      - name: Publish stable
        if: github.event.release.prerelease == false
        run: npm publish

      - name: Publish prerelease
        if: github.event.release.prerelease == true
        run: npm publish --tag next

      - name: Send Discord Notification
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            🚀 **Version ${{ github.event.release.tag_name }}** is now live on npm!
            📑 **What's New:**
            ${{ github.event.release.html_url }}
